version: "2"
services:
  cucumber-course:
    image: node:12
    container_name: cucumbercourse
    volumes:
      - ./app:/app
    working_dir: /app
    #command: bash -c "npm install && npm run server"
    command: npm run server
    ports:
      - "9090:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000